# Application routes

home:
  url: /
  module: main
  action: index

profile:
  url: /profile
  module: main
  action: profile

cards:
  url: /cards
  module: main
  action: cards

login:
  url: /login
  module: main
  action: login

logout:
  url: /logout
  module: main
  action: logout

register:
  url: /register
  module: main
  action: doregister

unavailable:
  url: /unavailable
  module: main
  action: unavailable

faq:
  url: /faq
  module: main
  action: faq

media:
  url: /media
  module: main
  action: media

admin:
  url: /admin
  module: admin
  action: index

edit_cards:
  url: /admin/:card_type/cards
  module: admin
  action: cards

admin_card_of_the_week:
  url: /admin/cotw
  module: admin
  action: cardoftheweek

admin_reset_user_cards:
  url: /admin/reset/usercards
  module: admin
  action: resetusercards

admin_reset_games:
  url: /admin/reset/games
  module: admin
  action: resetgames

admin_news:
  url: /admin/news
  module: admin
  action: news

create_news:
  url: /admin/news/edit
  module: admin
  action: editnews
  parameters: {mode: new}

create_attack:
  url: /admin/attack/edit
  module: admin
  action: editattack

edit_attack:
  url: /admin/attack/edit/:attack_id
  module: admin
  action: editattack

edit_news:
  url: /admin/news/edit/:id
  module: admin
  action: editnews

news:
  url: /news/:year/:month/:day/:title/:id
  module: main
  action: news

new_card:
  url: /admin/:card_type/card
  module: admin
  action: card

edit_card:
  url: /admin/:card_type/card/:card_id
  module: admin
  action: card

get_backdrop_partial:
  url: /get/backdroppartial/:key/*
  module: main
  action: getbackdroppartial

profile:
  url: /profile
  module: main
  action: profile

lobby:
  url: /lobby
  module: lobby
  action: index

ask:
  url: /ask
  module: ask
  action: ask

say:
  url: /say
  module: ask
  action: say

room_say:
  url: /room/:room_id/say
  module: lobby
  action: say

market:
  url: /market
  module: market
  action: index

board:
  url: /board/:game_id/*
  module: game
  action: board

leave_game:
  url: /leave/game/:game_id
  module: game
  action: leavegame

pick_cards:
  url: /cards/pick/:game_id/*
  module: game
  action: pickcards