# Application routes

home:
  url: /
  module: main
  action: index

login:
  url: /login
  module: main
  action: dologin

logout:
  url: /logout
  module: main
  action: logout

register:
  url: /register
  module: main
  action: doregister

admin:
  url: /admin
  module: admin
  action: index

edit_cards:
  url: /admin/:card_type/cards
  module: admin
  action: cards

new_card:
  url: /admin/:card_type/card
  module: admin
  action: card

edit_card:
  url: /admin/:card_type/card/:card_id
  module: admin
  action: card

get_backdrop_partial:
  url: /get/backdroppartial/:key
  module: main
  action: getbackdroppartial

profile:
  url: /profile
  module: main
  action: profile

lobby:
  url: /lobby
  module: main
  action: lobby

market:
  url: /market
  module: market
  action: index

board:
  url: /board/:game_id/*
  module: game
  action: board