# Application routes

home:
  url: /
  module: main
  action: index

login:
  url: /login
  module: main
  action: login

logout:
  url: /logout
  module: main
  action: logout

register:
  url: /register
  module: main
  action: doregister

unavailable:
  url: /unavailable
  module: main
  action: unavailable

faq:
  url: /faq
  module: main
  action: faq

media:
  url: /media
  module: main
  action: media

admin:
  url: /admin
  module: admin
  action: index

edit_cards:
  url: /admin/:card_type/cards
  module: admin
  action: cards

admin_card_of_the_week:
  url: /admin/cotw
  module: admin
  action: cardoftheweek

admin_news:
  url: /admin/news
  module: admin
  action: news

create_news:
  url: /admin/news/edit
  module: admin
  action: editnews
  parameters: {mode: new}

edit_news:
  url: /admin/news/edit/:id
  module: admin
  action: editnews

news:
  url: /news/:year/:month/:day/:title/:id
  module: main
  action: news

new_card:
  url: /admin/:card_type/card
  module: admin
  action: card

edit_card:
  url: /admin/:card_type/card/:card_id
  module: admin
  action: card

get_backdrop_partial:
  url: /get/backdroppartial/:key/*
  module: main
  action: getbackdroppartial

profile:
  url: /profile
  module: main
  action: profile

lobby:
  url: /lobby
  module: main
  action: lobby

market:
  url: /market
  module: market
  action: index

board:
  url: /board/:game_id/*
  module: game
  action: board